import { useState, useEffect, useRef } from 'react';
import { Copy, Download, Check } from 'lucide-react';

const APPLY_DEBOUNCE_MS = 400;

// Editable, two-way mirror of the project's SVG output.
//
//   - When the textarea is NOT focused, it tracks the `text` prop (which is
//     regenerated by App on every shape change).
//   - When the user types or pastes, edits debounce-parse via `onApply`. If
//     the text parses as SVG, the project's shapes are replaced silently.
//     If it doesn't parse, we just leave the project alone and surface a
//     small red status dot.
//   - On blur, the textarea re-syncs to the canonical `text` (whatever the
//     project actually is now). The user's intermediate keystrokes are
//     "lost" in the sense that they get replaced by the export's canonical
//     formatting — but the shape-level intent is preserved.
export default function CodePanel({ text, onApply, fileName = 'interactive-image.svg' }) {
  const [local, setLocal] = useState(text);
  const [status, setStatus] = useState('idle'); // 'idle' | 'ok' | 'error'
  const [copied, setCopied] = useState(false);
  const focusedRef = useRef(false);
  const timerRef = useRef(null);

  // Local undo / redo stacks for the textarea. React controlled inputs
  // wipe the browser's native undo state, so we keep our own.
  // Cap at 200 entries to avoid unbounded growth.
  const undoStackRef = useRef([]);
  const redoStackRef = useRef([]);
  const MAX_HISTORY = 200;

  useEffect(() => {
    if (!focusedRef.current) {
      setLocal(text);
      setStatus('idle');
      // Snapshot from outside (canvas edits) shouldn't be undoable
      // through the textarea's own stack.
      undoStackRef.current = [];
      redoStackRef.current = [];
    }
  }, [text]);

  const tryApply = (v) => {
    const t = v.trim();
    if (!t) {
      setStatus('idle');
      return;
    }
    if (!looksLikeSvg(t)) {
      setStatus('error');
      return;
    }
    try {
      onApply(t);
      setStatus('ok');
    } catch {
      setStatus('error');
    }
  };

  const pushUndo = (prev) => {
    const stack = undoStackRef.current;
    if (stack[stack.length - 1] === prev) return; // dedupe rapid identical
    stack.push(prev);
    if (stack.length > MAX_HISTORY) stack.shift();
    redoStackRef.current = []; // new edit invalidates redo
  };

  const onChange = (e) => {
    const v = e.target.value;
    pushUndo(local);
    setLocal(v);
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => tryApply(v), APPLY_DEBOUNCE_MS);
  };

  const undo = () => {
    const stack = undoStackRef.current;
    if (!stack.length) return;
    redoStackRef.current.push(local);
    const prev = stack.pop();
    setLocal(prev);
    // Apply the reverted text so canvas stays in sync with what's shown.
    if (timerRef.current) clearTimeout(timerRef.current);
    tryApply(prev);
  };

  const redo = () => {
    const stack = redoStackRef.current;
    if (!stack.length) return;
    undoStackRef.current.push(local);
    const next = stack.pop();
    setLocal(next);
    if (timerRef.current) clearTimeout(timerRef.current);
    tryApply(next);
  };

  const onKeyDown = (e) => {
    const ctrl = e.ctrlKey || e.metaKey;
    if (!ctrl) return;
    if ((e.key === 'z' || e.key === 'Z') && !e.shiftKey) {
      e.preventDefault();
      e.stopPropagation();
      undo();
    } else if (((e.key === 'z' || e.key === 'Z') && e.shiftKey) || e.key === 'y' || e.key === 'Y') {
      e.preventDefault();
      e.stopPropagation();
      redo();
    }
  };

  const onFocus = () => { focusedRef.current = true; };
  const onBlur = () => {
    focusedRef.current = false;
    // Flush any pending parse so blur doesn't drop the user's last edit.
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      tryApply(local);
    }
    // Snap to canonical export (or keep local if there's no project yet).
    if (text) setLocal(text);
  };

  const copy = async () => {
    if (!local) return;
    try {
      await navigator.clipboard.writeText(local);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {}
  };

  const download = () => {
    if (!local) return;
    const blob = new Blob([local], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col min-h-0 flex-1">
      <div className="h-10 px-3 flex items-center justify-between border-b border-[#1f1f22] flex-shrink-0">
        <div className="flex items-center gap-2">
          <span className="text-[11px] uppercase tracking-wider text-[#6a6a70] font-medium">
            SVG output
          </span>
          <StatusDot status={status} />
        </div>
        <div className="flex items-center gap-1">
          <IconBtn onClick={copy} disabled={!local} title="Copy">
            {copied ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
          </IconBtn>
          <IconBtn onClick={download} disabled={!local} title="Download">
            <Download size={12} />
          </IconBtn>
        </div>
      </div>
      <textarea
        value={local}
        onChange={onChange}
        onKeyDown={onKeyDown}
        onFocus={onFocus}
        onBlur={onBlur}
        spellCheck={false}
        placeholder="Paste or type SVG markup here…&#10;&#10;Live edits sync to the canvas as you go."
        className="flex-1 min-h-0 resize-none p-3 text-[11px] font-mono leading-relaxed text-[#c4c4c8] bg-[#0a0a0c] outline-none border-none"
        style={{ whiteSpace: 'pre', overflowWrap: 'normal' }}
      />
    </div>
  );
}

function looksLikeSvg(t) {
  return /^\s*<(?:\?xml|svg)/i.test(t);
}

function StatusDot({ status }) {
  if (status === 'idle') return null;
  const color = status === 'ok' ? '#4ade80' : '#f87171';
  const title = status === 'ok' ? 'Applied' : 'Parse error';
  return (
    <div
      className="w-1.5 h-1.5 rounded-full"
      style={{ background: color }}
      title={title}
    />
  );
}

function IconBtn({ children, onClick, disabled, title }) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      title={title}
      className="w-7 h-7 flex items-center justify-center rounded text-[#9a9aa0] hover:bg-[#1f1f22] hover:text-white disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
    >
      {children}
    </button>
  );
}
